[package]
name = "verification"
version = "0.1.0"
edition = "2021"

[dependencies]
lombok = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
users = "0.11.0"
